# DataFrames I

In [1]:
import pandas as pd

## Methods and Attributes between Series and DataFrames
- A `DataFrame` is a 2-dimensional table consisting of rows and columns.
- Like with a `Series`, Pandas assigns an index position/label to each `DataFrame` row.
- Pandas uses a `NaN` designation for cells that have a missing value.
- The `pd.read_csv` function imports a `DataFrame` by default.
- The `nba.csv` dataset is a collection of basketball players.
- The last row in the dataset is completely empty.

In [2]:
nba = pd.read_csv("nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
...,...,...,...,...,...,...,...
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


- The `DataFrame` and `Series` have common and exclusive methods/attributes.
- Some methods/attributes will return different types of data.

In [3]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

- The `head` method returns rows from the start of the `DataFrame`.
- The `tail` method returns rows from the end of the `DataFrame`.

In [4]:
nba.head()
nba.head(n=5)
nba.head(8)

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
5,Corey Kispert,Atlanta Hawks,F,6-6,224.0,Gonzaga,13500000.0
6,Dyson Daniels,Atlanta Hawks,G,6-7,199.0,G League Ignite,21500000.0
7,Gabe Vincent,Atlanta Hawks,G,6-3,200.0,UC Santa Barbara,11500000.0


In [5]:
nba.tail()
nba.tail(n=7)

,Name,Team,Position,Height,Weight,College,Salary
520,Leaky Black,Washington Wizards,F,6-9,218.0,North Carolina,600000.0
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0
526,NaN,NaN,NaN,NaN,NaN,NaN,NaN


- The `index` attribute stores the object that holds the index labels.

In [6]:
s.index
nba.index

RangeIndex(start=0, stop=527, step=1)

- The `shape` attribute is a tuple with the dimensions (height x width) of the data structure.

In [7]:
s.shape
nba.shape

(527, 7)

- The `dtypes` attribute holds the data types.
- The `DataFrame` has multiple columns, so Pandas creates a `Series` where the index labels are the column names and the values are their data types.

In [8]:
s.dtypes
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

- The `hasnans` attribute returns `True` if a `Series` contains any missing values.
- The attribute does not exist on a `DataFrame`.

In [9]:
s.hasnans
# nba.hasnans

False

- The `columns` attribute returns the column labels of a `DataFrame`.
- The attribute does not exist on a `Series`.

In [10]:
nba.columns
# s.columns

Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='str')

- The `axes` attribute returns a list of the axis indexes.
- The `Series` has only one index, so the list has 1 entry.
- The `DataFrame` has two indexes (rows and columns), so the list has 2 entries.

In [11]:
s.axes
nba.axes

[RangeIndex(start=0, stop=527, step=1),
 Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='str')]

- The `info` method returns a summary of the pandas object.
- The output includes the index type, a count of non-null values, the data types, and the memory usage.

In [12]:
s.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes


- The `info` method on a `DataFrame` outputs the details _per_ column.

In [13]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 527 entries, 0 to 526
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      526 non-null    str    
 1   Team      526 non-null    str    
 2   Position  526 non-null    str    
 3   Height    526 non-null    str    
 4   Weight    526 non-null    float64
 5   College   485 non-null    str    
 6   Salary    474 non-null    float64
dtypes: float64(2), str(5)
memory usage: 50.8 KB


## Differences between Shared Methods
- The same method may work differently on a `Series` vs. a `DataFrame`.

In [14]:
s = pd.Series([1, 2, 3, 4, 5])
revenue = pd.read_csv("revenue.csv", index_col="Date")
revenue.head()

,New York,Los Angeles,Miami
Date,,,
1/1/26,985,122,499
1/2/26,738,788,534
1/3/26,14,20,933
1/4/26,730,904,885
1/5/26,114,71,253


- The `sum` method adds a `Series`'s values. There is only one direction to add.

In [15]:
s.sum()
s.sum(axis="index")
s.sum(axis=0)

np.int64(15)

In [16]:
s.axes

[RangeIndex(start=0, stop=5, step=1)]

- On a `DataFrame`, the `sum` method defaults to adding the column values.
- The method returns a `Series` where the index labels are the column names and the values are the sum totals.
- The `axis` parameter customizes the direction that we add across. Pass `"index"` or `0` to add values by traversing the rows.

In [17]:
revenue.sum()
revenue.sum(axis="index")
revenue.sum(axis=0)

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

- Pass the `axis` parameter an argument of `"columns"` to calculate the sum of each row's values.
- We are traversing the "columns" in calculating the sum rather than traversing the "index".

In [18]:
revenue.sum(axis="columns")
revenue.sum(axis=1)

Date
1/1/26     1606
1/2/26     2060
1/3/26      967
1/4/26     2519
1/5/26      438
1/6/26     1935
1/7/26     1234
1/8/26     2313
1/9/26     2623
1/10/26     555
dtype: int64

In [19]:
revenue.axes

[Index(['1/1/26', '1/2/26', '1/3/26', '1/4/26', '1/5/26', '1/6/26', '1/7/26',
        '1/8/26', '1/9/26', '1/10/26'],
       dtype='str', name='Date'),
 Index(['New York', 'Los Angeles', 'Miami'], dtype='str')]

- Now that we have a `Series` of numbers, we can also calculate total business revenue by invoking `sum`.

In [20]:
revenue.sum(axis=1).sum()

revenue.sum(axis=0).sum()

np.int64(16250)

## Select One Column from a DataFrame

In [21]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN


- Pandas will define a `DataFrame` attribute for each column name.
- Use attribute syntax (`df.column_name`) to select a column.
- Pandas extracts the `DataFrame` column as a `Series`.

In [22]:
nba.Name
nba.Salary

0       4000000.0
1       9700000.0
2      30700000.0
3       1300000.0
4             NaN
          ...    
522    47500000.0
523     9400000.0
524     3000000.0
525     4300000.0
526           NaN
Name: Salary, Length: 527, dtype: float64

In [23]:
type(nba.Team)

pandas.Series

- Case-sensitivity matters. Write out the column name with correct capitalization.
- The attribute accesssyntax will not work if the column name has spaces.

In [24]:
# nba.team

- The extracted column is a valid `Series` with all of its regular methods.
- The `value_counts` counts the number of times that each distinct value occurs.

In [25]:
nba.Team.value_counts()

Team
Charlotte Hornets         18
Chicago Bulls             18
Cleveland Cavaliers       18
Dallas Mavericks          18
Denver Nuggets            18
Detroit Pistons           18
Indiana Pacers            18
Los Angeles Clippers      18
Los Angeles Lakers        18
Miami Heat                18
Milwaukee Bucks           18
Minnesota Timberwolves    18
New York Knicks           18
Oklahoma City Thunder     18
Philadelphia 76ers        18
Phoenix Suns              18
San Antonio Spurs         18
Washington Wizards        18
Atlanta Hawks             17
Brooklyn Nets             17
Golden State Warriors     17
Houston Rockets           17
Memphis Grizzlies         17
New Orleans Pelicans      17
Orlando Magic             17
Portland Trail Blazers    17
Sacramento Kings          17
Toronto Raptors           17
Utah Jazz                 17
Boston Celtics            15
Name: count, dtype: int64

- Square bracket syntax also extracts a column (`df["column name"]`).
- The syntax will not work if the column name has spaces or special symbols.

In [26]:
nba["Team"]
nba["Salary"]

0       4000000.0
1       9700000.0
2      30700000.0
3       1300000.0
4             NaN
          ...    
522    47500000.0
523     9400000.0
524     3000000.0
525     4300000.0
526           NaN
Name: Salary, Length: 527, dtype: float64

- Recall Pandas 3's **Copy-on-Write** principles.
- Extracting a column returns an object that behaves as a copy.
- The underlying data is still shared between `Series` and `DataFrame`.
- When we perform a mutative operation on the `Series`, Pandas will create a copy of the underlying data.
- In summary, mutating the extracted `Series` will **not** mutate the original `DataFrame`.

In [27]:
players = nba["Name"]
players

0            Asa Newell
1           Buddy Hield
2         C.J. McCollum
3         Caleb Houstan
4      Christian Koloko
             ...       
522          Trae Young
523         Tre Johnson
524    Tristan Vukcevic
525          Will Riley
526                 NaN
Name: Name, Length: 527, dtype: str

In [28]:
players.iloc[0] = "Mr. Bob Basketball"

In [29]:
players.head()

0    Mr. Bob Basketball
1           Buddy Hield
2         C.J. McCollum
3         Caleb Houstan
4      Christian Koloko
Name: Name, dtype: str

In [30]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN


## Select Multiple Columns from a DataFrame
- Use square brackets with a list of column names to extract multiple `DataFrame` columns.
- Pandas stores the result in a new `DataFrame` that behaves like a copy.

In [31]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN


In [32]:
nba[["Name", "Team"]]

,Name,Team
0,Asa Newell,Atlanta Hawks
1,Buddy Hield,Atlanta Hawks
2,C.J. McCollum,Atlanta Hawks
3,Caleb Houstan,Atlanta Hawks
4,Christian Koloko,Atlanta Hawks
...,...,...
522,Trae Young,Washington Wizards
523,Tre Johnson,Washington Wizards
524,Tristan Vukcevic,Washington Wizards
525,Will Riley,Washington Wizards


- The order of list elements impacts the order of the `DataFrame`'s columns.

In [33]:
nba[["Team", "Name"]]

,Team,Name
0,Atlanta Hawks,Asa Newell
1,Atlanta Hawks,Buddy Hield
2,Atlanta Hawks,C.J. McCollum
3,Atlanta Hawks,Caleb Houstan
4,Atlanta Hawks,Christian Koloko
...,...,...
522,Washington Wizards,Trae Young
523,Washington Wizards,Tre Johnson
524,Washington Wizards,Tristan Vukcevic
525,Washington Wizards,Will Riley


- Assign the list to a variable for an easier syntax.

In [34]:
columns_to_select = ["Salary", "Team", "Name"]

nba[columns_to_select]

,Salary,Team,Name
0,4000000.0,Atlanta Hawks,Asa Newell
1,9700000.0,Atlanta Hawks,Buddy Hield
2,30700000.0,Atlanta Hawks,C.J. McCollum
3,1300000.0,Atlanta Hawks,Caleb Houstan
4,NaN,Atlanta Hawks,Christian Koloko
...,...,...,...
522,47500000.0,Washington Wizards,Trae Young
523,9400000.0,Washington Wizards,Tre Johnson
524,3000000.0,Washington Wizards,Tristan Vukcevic
525,4300000.0,Washington Wizards,Will Riley


## Add New Column to DataFrame
- Use square bracket extraction syntax with an equal sign to add a new `Series` to a `DataFrame`.
- Be careful here. If you reference an existing column, Pandas will overwrite it.

In [35]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN


In [36]:
nba["Sport"] = "Basketball"

In [37]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary,Sport
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0,Basketball
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0,Basketball
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0,Basketball
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0,Basketball
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN,Basketball


- The `insert` method adds an column at a specific column index.
- The `insert` method mutates the existing `DataFrame`. It does not return a value.
- The column index starts counting from 0. The `Name` column is index 0.
- `loc=3` means the new columns becomes the 4th column (after `Position`).

In [38]:
nba.insert(loc=3, column="League", value="NBA")

In [39]:
nba.head()

,Name,Team,Position,League,Height,Weight,College,Salary,Sport
0,Asa Newell,Atlanta Hawks,F,NBA,6-10,220.0,Georgia,4000000.0,Basketball
1,Buddy Hield,Atlanta Hawks,G-F,NBA,6-4,220.0,Oklahoma,9700000.0,Basketball
2,C.J. McCollum,Atlanta Hawks,G,NBA,6-3,190.0,Lehigh,30700000.0,Basketball
3,Caleb Houstan,Atlanta Hawks,F,NBA,6-8,205.0,Michigan,1300000.0,Basketball
4,Christian Koloko,Atlanta Hawks,C,NBA,7-0,230.0,Arizona,NaN,Basketball


- The right-hand side of the equal sign can also be a `Series`.
- Let's imagine a scenario where each player's salary doubled.

In [40]:
nba["Salary Doubled"] = nba["Salary"].mul(2)

In [41]:
nba.head()

,Name,Team,Position,League,Height,Weight,College,Salary,Sport,Salary Doubled
0,Asa Newell,Atlanta Hawks,F,NBA,6-10,220.0,Georgia,4000000.0,Basketball,8000000.0
1,Buddy Hield,Atlanta Hawks,G-F,NBA,6-4,220.0,Oklahoma,9700000.0,Basketball,19400000.0
2,C.J. McCollum,Atlanta Hawks,G,NBA,6-3,190.0,Lehigh,30700000.0,Basketball,61400000.0
3,Caleb Houstan,Atlanta Hawks,F,NBA,6-8,205.0,Michigan,1300000.0,Basketball,2600000.0
4,Christian Koloko,Atlanta Hawks,C,NBA,7-0,230.0,Arizona,NaN,Basketball,NaN


- Here's another example with subtraction.

In [42]:
nba["Salary"] = nba["Salary"].sub(500000)

In [43]:
nba.head()

,Name,Team,Position,League,Height,Weight,College,Salary,Sport,Salary Doubled
0,Asa Newell,Atlanta Hawks,F,NBA,6-10,220.0,Georgia,3500000.0,Basketball,8000000.0
1,Buddy Hield,Atlanta Hawks,G-F,NBA,6-4,220.0,Oklahoma,9200000.0,Basketball,19400000.0
2,C.J. McCollum,Atlanta Hawks,G,NBA,6-3,190.0,Lehigh,30200000.0,Basketball,61400000.0
3,Caleb Houstan,Atlanta Hawks,F,NBA,6-8,205.0,Michigan,800000.0,Basketball,2600000.0
4,Christian Koloko,Atlanta Hawks,C,NBA,7-0,230.0,Arizona,NaN,Basketball,NaN


## Create Columns with the assign Method
- The `assign` method returns a new `DataFrame`  with one or more new columns.
- The method differs from direct assignment (`df["col"] = value`), which **mutates** the original `DataFrame`.

In [44]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN


- Pass keyword arguments where the parameter is the new column name and the value is a `Series`.

In [45]:
nba.assign(Salary_Doubled=nba["Salary"] * 2, Weight_Minus_10=nba["Weight"] - 10.5)

,Name,Team,Position,Height,Weight,College,Salary,Salary_Doubled,Weight_Minus_10
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0,8000000.0,209.5
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0,19400000.0,209.5
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0,61400000.0,179.5
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0,2600000.0,194.5
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN,NaN,219.5
...,...,...,...,...,...,...,...,...,...
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0,95000000.0,153.5
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0,18800000.0,179.5
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0,6000000.0,209.5
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0,8600000.0,175.5


In [46]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN


## Drop Rows with Missing Values
- Pandas designates missing values with a `NaN`.

In [47]:
nba = pd.read_csv("nba.csv")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0
526,NaN,NaN,NaN,NaN,NaN,NaN,NaN


- The `dropna` method deletes rows with missing values.
- The method's default behavior is to remove a row if it contains *any* missing values.

In [48]:
nba.dropna()
nba.dropna(how="any")

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
5,Corey Kispert,Atlanta Hawks,F,6-6,224.0,Gonzaga,13500000.0
...,...,...,...,...,...,...,...
519,Kyshawn George,Washington Wizards,G-F,6-8,205.0,Miami (FL),3800000.0
520,Leaky Black,Washington Wizards,F,6-9,218.0,North Carolina,600000.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0


- Pass the `how` parameter an argument of "all" to remove rows where all the values are `NaN`.
- This solution effectively removes the final `DataFrame` rows which holds only missing values.

In [49]:
nba.dropna(how="all")

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0


- The `subset` parameter limits the columns that pandas will use to drop rows with missing values.
- The next example drop rows with a missing value in either the `College` or `Salary` column (or both).

In [50]:
nba.dropna(subset=["College"])
nba.dropna(subset=["College", "Salary"])

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
5,Corey Kispert,Atlanta Hawks,F,6-6,224.0,Gonzaga,13500000.0
...,...,...,...,...,...,...,...
519,Kyshawn George,Washington Wizards,G-F,6-8,205.0,Miami (FL),3800000.0
520,Leaky Black,Washington Wizards,F,6-9,218.0,North Carolina,600000.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0


- The `thresh` parameter keeps rows with a minimum number of present values.
- `thresh` is useful when some missing data is acceptable and you want to drop rows that are *mostly* empty.
- The next example passes an argument of 5, which keeps rows with at least 5 non-null values (out of 7 columns).

In [51]:
nba.dropna(thresh=5)

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0


## Fill in Missing Values with the fillna Method
- The `fillna` method replaces missing `NaN` values with its argument.
- The `fillna` method is available on both `DataFrame` and `Series` objects.
- The `fillna` method returns a new object with missing values replaced.  The original is not mutated.

In [52]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


In [53]:
nba.fillna(0)

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0.0
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,0,3000000.0


- Pass `fillna` a **dictionary** to specify replacement values _per_ column.
- The dictionary keys will be the column names, and the dictionary values are the replacement values.

In [54]:
nba.fillna({"Salary": 0, "College": "Unknown", "Position": "N/A"})

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0.0
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,Unknown,3000000.0


- The next example replaces `NaN` values with 0 in the `Salary` column.

In [55]:
nba["Salary"] = nba["Salary"].fillna(0)

In [56]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0.0
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0


In [57]:
nba["College"] = nba["College"].fillna(value="Unknown")

In [58]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0.0
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,Unknown,3000000.0


## Fill Missing Values with a Forward Fill or Back Fill
- Forward fills and backward fills are two alternate stategies for replacing missing values.
- Fills are ideal when the previous or next observation is a reasonable estimate for a missing value.
- The `temperatures.csv` file has missing values in the `High Temp` column.
- Example: When measuring temperatures, it's reasonable to guess that a day's temperature will be similar to the one on the previous or next day.

In [59]:
temperatures = pd.read_csv("temperatures.csv")
temperatures.head()

,Date,High Temp
0,2026-01-01,34.0
1,2026-01-02,36.0
2,2026-01-03,33.0
3,2026-01-04,NaN
4,2026-01-05,38.0


- The `ffill` method **forward-fills** missing values.
- Pandas replaces each `NaN` with the last valid value above it.
- For example, index 2's value of 33.0 replaces index 3's missing `NaN` value.

In [60]:
temperatures["High Temp"].ffill()

0     34.0
1     36.0
2     33.0
3     33.0
4     38.0
5     41.0
6     43.0
7     45.0
8     44.0
9     44.0
10    44.0
11    44.0
12    39.0
13    37.0
14    35.0
15    32.0
16    30.0
17    28.0
18    31.0
19    33.0
20    33.0
21    36.0
22    38.0
23    40.0
24    42.0
25    42.0
26    44.0
27    43.0
28    41.0
29    39.0
30    37.0
Name: High Temp, dtype: float64

- The `bfill` method **backward-fills** missing values.
- Pandas replaces each `NaN` with the next valid value below it.
- For example, index 4's value of 38.0 replaces index 3's missing `NaN` value.

In [61]:
temperatures["High Temp"].bfill()

0     34.0
1     36.0
2     33.0
3     38.0
4     38.0
5     41.0
6     43.0
7     45.0
8     44.0
9     39.0
10    39.0
11    39.0
12    39.0
13    37.0
14    35.0
15    32.0
16    30.0
17    28.0
18    31.0
19    33.0
20    36.0
21    36.0
22    38.0
23    40.0
24    42.0
25    44.0
26    44.0
27    43.0
28    41.0
29    39.0
30    37.0
Name: High Temp, dtype: float64

- The `limit` parameter places a boundary on how many consecutive `NaN` values to fill.
- The values at row indexes 9, 10, and 11 are all `NaN`.
- An argument of 1 replaces 1 `NaN` value in the sequence (index 9) while keeping the other `NaN`s (index 10, 11).

In [62]:
temperatures["High Temp"].ffill(limit=2)

0     34.0
1     36.0
2     33.0
3     33.0
4     38.0
5     41.0
6     43.0
7     45.0
8     44.0
9     44.0
10    44.0
11     NaN
12    39.0
13    37.0
14    35.0
15    32.0
16    30.0
17    28.0
18    31.0
19    33.0
20    33.0
21    36.0
22    38.0
23    40.0
24    42.0
25    42.0
26    44.0
27    43.0
28    41.0
29    39.0
30    37.0
Name: High Temp, dtype: float64

## Convert Data Types with the astype Method I
- The `astype` method converts a `Series's` values to a specified type.
- Developers sometimes use the word "cast" to describe type conversion (i.e., "we cast this number from int to float').
- Pandas cannot convert `NaN` values to numeric types, so we need to eliminate/replace them before we perform the conversion.

In [63]:
nba = pd.read_csv("nba.csv").dropna(how="all").fillna({"Salary": 0})
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


- Pass in the specified type as either a string or the core Python data type.
- The `dtypes` attribute returns a `Series` with the `DataFrame`'s columns and their types.

In [64]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [65]:
nba["Salary"].astype("int")
nba["Salary"].astype(int)

0       4000000
1       9700000
2      30700000
3       1300000
4             0
         ...   
521           0
522    47500000
523     9400000
524     3000000
525     4300000
Name: Salary, Length: 526, dtype: int64

- We can then use the assignment operator (`=`) to replace the column.

In [66]:
nba["Salary"] = nba["Salary"].astype(int)

In [67]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary        int64
dtype: object

- The second option is to invoke `astype` on the `DataFrame` and pass in a dictionary.
- The keys should be the column names, and the values should be the desired data types.

In [68]:
nba.astype({"Salary": int})

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0
...,...,...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000


- A 64-bit integer (`int64`) can represent values from -9,223,372,036,854,775,808 (quadrillion) to 9,223,372,036,854,775,807.
- A 32-bit integer (`int32`) can represent values from -2,147,483,648 to 2,147,483,647.
- A 16-bit integer (`int16`) can represent values from -32,768 to 32,767.
- A 32-bit integer should be large enough to model every salary in the dataset.
- The `memory_usage` method returns the amount of bytes that each columnn's data occupies in memory.

In [69]:
nba.memory_usage()
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      526 non-null    str    
 1   Team      526 non-null    str    
 2   Position  526 non-null    str    
 3   Height    526 non-null    str    
 4   Weight    526 non-null    float64
 5   College   485 non-null    str    
 6   Salary    526 non-null    int64  
dtypes: float64(1), int64(1), str(5)
memory usage: 50.8 KB


- Pass the `astype` method an instance of a data type at the top-level of pandas.

In [70]:
nba["Salary"] = nba["Salary"].astype(pd.Int32Dtype())

- The data type will update from `int64` to `Int32`.
- Notice the difference in casing. The two are actually different types from different libraries.
- `int64` comes from `numpy` and `Int32` comes from Pandas.
- The Pandas integers support missing values, while the NumPy integers do not support them.

In [71]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary        Int32
dtype: object

In [72]:
nba.memory_usage()
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      526 non-null    str    
 1   Team      526 non-null    str    
 2   Position  526 non-null    str    
 3   Height    526 non-null    str    
 4   Weight    526 non-null    float64
 5   College   485 non-null    str    
 6   Salary    526 non-null    Int32  
dtypes: Int32(1), float64(1), str(5)
memory usage: 49.2 KB


In [73]:
nba["Weight"] = nba["Weight"].astype(pd.Int16Dtype())

In [74]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      526 non-null    str  
 1   Team      526 non-null    str  
 2   Position  526 non-null    str  
 3   Height    526 non-null    str  
 4   Weight    526 non-null    Int16
 5   College   485 non-null    str  
 6   Salary    526 non-null    Int32
dtypes: Int16(1), Int32(1), str(5)
memory usage: 46.7 KB


## Convert to Numbers with the to_numeric Function
- The `pd.to_numeric` function converts values to a numeric type (`int` or `float`).

In [75]:
messy = pd.Series(["10", "20", "thirty", "", "40", "50.5"])
messy

0        10
1        20
2    thirty
3          
4        40
5      50.5
dtype: str

- The `astype` method will fail if Pandas cannot convert a value to the specified type.

In [76]:
# messy.astype(int)

- The `pd.to_numeric` function attempts to convert to a numeric data type (integer or float)
- The `errors` parameter sets what happens when Pandas cannot convert a value.
- An argument of `raise` (the default) raises an exception on failure.
- An argument of `coerce` converts failures to `NaN`.

In [77]:
pd.to_numeric(messy, errors="coerce").dropna().astype(int)

0    10
1    20
4    40
5    50
dtype: int64

## Select Columns by Type with the select_dtypes Method
- The `select_dtypes` method targets columns by their data types.
- The `include` and `exclude` parameters both accept data types as strings.
- The `include` parameter keeps the columns matching the specified type(s) (e.g., `"number"`, `"str"`, `"category"`).
- The `exclude` parameter drops columns matching the specified type.

In [78]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


In [79]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

- The next example targets all numeric columns (integers and floats).

In [80]:
nba.select_dtypes(include="number")
nba.select_dtypes(include="string")

,Name,Team,Position,Height,College
0,Asa Newell,Atlanta Hawks,F,6-10,Georgia
1,Buddy Hield,Atlanta Hawks,G-F,6-4,Oklahoma
2,C.J. McCollum,Atlanta Hawks,G,6-3,Lehigh
3,Caleb Houstan,Atlanta Hawks,F,6-8,Michigan
4,Christian Koloko,Atlanta Hawks,C,7-0,Arizona
...,...,...,...,...,...
521,Sharife Cooper,Washington Wizards,G,6-1,Auburn
522,Trae Young,Washington Wizards,G,6-1,Oklahoma
523,Tre Johnson,Washington Wizards,G,6-5,Texas
524,Tristan Vukcevic,Washington Wizards,C,6-11,NaN


- The next example targets string columns

In [81]:
nba.select_dtypes(exclude="number")
nba.select_dtypes(exclude="string")

,Weight,Salary
0,220.0,4000000.0
1,220.0,9700000.0
2,190.0,30700000.0
3,205.0,1300000.0
4,230.0,NaN
...,...,...
521,180.0,NaN
522,164.0,47500000.0
523,190.0,9400000.0
524,220.0,3000000.0


## Convert Data Types with the astype Method II: Categories
- The `category` type is ideal for columns with a limited number of unique values.
- For categories, pandas does not create a separate copy of every string/cell in memory. 
- Rather, Pandas connects each distinct string to a numeric representation. Integers are cheaper to store in memory than strings.

In [82]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


- The `nunique` method returns a count of the number of unique values per column.

In [83]:
nba["Team"].nunique()
nba["Position"].nunique()
nba["Name"].nunique()

526

In [84]:
nba.nunique()

Name        526
Team         30
Position      5
Height       19
Weight       84
College     137
Salary      199
dtype: int64

In [85]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      526 non-null    str    
 1   Team      526 non-null    str    
 2   Position  526 non-null    str    
 3   Height    526 non-null    str    
 4   Weight    526 non-null    float64
 5   College   485 non-null    str    
 6   Salary    474 non-null    float64
dtypes: float64(2), str(5)
memory usage: 50.8 KB


- The `Position` and `Team` columns are good candidates to be category columns.
- There are 7 unique positions and 30 unique teams in a DataFrame with ~600 rows.

In [86]:
nba["Position"] = nba["Position"].astype("category")

In [87]:
nba["Team"] = nba["Team"].astype("category")

- Converting to `category` reduces memory usage.

In [88]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Name      526 non-null    str     
 1   Team      526 non-null    category
 2   Position  526 non-null    category
 3   Height    526 non-null    str     
 4   Weight    526 non-null    float64 
 5   College   485 non-null    str     
 6   Salary    474 non-null    float64 
dtypes: category(2), float64(2), str(3)
memory usage: 35.2 KB


- We've reduced the memory by nearly a third!

In [89]:
35.2 / 50.8

0.6929133858267718

In [90]:
# Atlanta Hawks <- 0
# Los Angeles Lakers -> 1

In [91]:
nba.dtypes

Name             str
Team        category
Position    category
Height           str
Weight       float64
College          str
Salary       float64
dtype: object

## Attribute Namespaces
- Pandas nests related methods underneath attributes/namespaces.

In [92]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba["Position"] = nba["Position"].astype("category")
nba["Team"] = nba["Team"].astype("category")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


- For example, the `str` attribute holds string methods.

In [93]:
nba["Team"].str.upper()
nba["Team"].str.lower()

nba["Team"].str.upper().str.lower()

0           atlanta hawks
1           atlanta hawks
2           atlanta hawks
3           atlanta hawks
4           atlanta hawks
              ...        
521    washington wizards
522    washington wizards
523    washington wizards
524    washington wizards
525    washington wizards
Name: Team, Length: 526, dtype: object

- The `cat` namespace holds methods for categorical columns.
- The `cat.categories` attribute returns the distinct categories for a categorical column.

In [94]:
nba["Position"].cat.categories

Index(['C', 'F', 'F-C', 'G', 'G-F'], dtype='str')

## Sort a DataFrame with the sort_values Method I
- The `sort_values` method sorts a `DataFrame` by the values in one or more columns.
- If sorting by a single column, pass a string with its name.
- The default sort order is ascending (alphabetical for strings).
- The first parameter (`by`) expects the column(s) to sort by.
- The `ascending` parameter customizes the sort order.
- The `na_position` parameter customizes where pandas places `NaN` values.

In [95]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


In [96]:
nba.sort_values("Name")
nba.sort_values(by="Name")
nba.sort_values(by="Name", ascending=True)
nba.sort_values(by="Name", ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
315,Zyon Pullin,Minnesota Timberwolves,G,6-4,206.0,Florida,NaN
332,Zion Williamson,New Orleans Pelicans,F,6-7,284.0,Duke,42200000.0
48,Ziaire Williams,Brooklyn Nets,F,6-8,185.0,Stanford,6000000.0
138,Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,7700000.0
455,Zach LaVine,Sacramento Kings,G-F,6-5,200.0,UCLA,48200000.0
...,...,...,...,...,...,...,...
174,Aaron Holiday,Houston Rockets,G,6-0,185.0,UCLA,2300000.0
121,Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,31600000.0
103,AJ Johnson,Dallas Mavericks,G,6-5,160.0,NaN,3900000.0
474,A.J. Lawson,Toronto Raptors,G,6-6,178.0,South Carolina,NaN


In [97]:
nba.sort_values("Salary")
nba.sort_values("Salary", ascending=True)
nba.sort_values("Salary", ascending=False)
nba.sort_values("Salary", na_position="last")
nba.sort_values("Salary", na_position="first")
nba.sort_values("Salary", na_position="first", ascending=False)
nba.sort_values("Salary", ascending=False, na_position="first")

,Name,Team,Position,Height,Weight,College,Salary
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
23,John Tonje,Boston Celtics,G,6-5,218.0,Wisconsin,NaN
30,Ron Harper Jr.,Boston Celtics,G-F,6-6,245.0,Rutgers,NaN
37,E.J. Liddell,Brooklyn Nets,F,6-7,240.0,Ohio State,NaN
49,Antonio Reeves,Charlotte Hornets,G,6-6,195.0,Kentucky,NaN
...,...,...,...,...,...,...,...
146,Isaac Jones,Detroit Pistons,C,6-9,242.0,Washington State,600000.0
492,Blake Hinson,Utah Jazz,F,6-7,235.0,Pittsburgh,600000.0
334,Dillon Jones,New York Knicks,F,6-6,235.0,Weber State,600000.0
464,Harrison Ingram,San Antonio Spurs,G,6-6,230.0,North Carolina,600000.0


## Sort a DataFrame with the sort_values Method II: Multiple Columns
- To sort by multiple columns, pass the `by` parameter a list of column names. Pandas will sort in the specified column order (first to last).
- Pass the `ascending` parameter a Boolean to sort all columns in a consistent order (all ascending or all descending).
- Pass `ascending` a list to customize the sort order *per* column. The `ascending` list length must match the `by` list.

In [98]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


In [99]:
nba.sort_values(["Team", "Name"])
nba.sort_values(by=["Team", "Name"])
nba.sort_values(by=["Team", "Name"], ascending=True)
nba.sort_values(by=["Team", "Name"], ascending=False)
nba.sort_values(by=["Team", "Name"], ascending=[True, False])

,Name,Team,Position,Height,Weight,College,Salary
16,Zaccharie Risacher,Atlanta Hawks,F,6-8,215.0,NaN,14800000.0
15,RayJ Dennis,Atlanta Hawks,G,6-2,180.0,Baylor,600000.0
14,Onyeka Okongwu,Atlanta Hawks,C,6-8,235.0,USC,16000000.0
13,Nickeil Alexander-Walker,Atlanta Hawks,G-F,6-5,205.0,Virginia Tech,15200000.0
12,Mouhamed Gueye,Atlanta Hawks,C,6-10,210.0,Washington State,2100000.0
...,...,...,...,...,...,...,...
512,Bub Carrington,Washington Wizards,G,6-5,190.0,Pittsburgh,5600000.0
511,Bilal Coulibaly,Washington Wizards,F,6-8,180.0,NaN,8300000.0
510,Anthony Gill,Washington Wizards,F,6-7,230.0,Virginia,2300000.0
509,Anthony Davis,Washington Wizards,F-C,6-10,253.0,Kentucky,58400000.0


In [100]:
nba.sort_values(["Position", "Salary"])
nba.sort_values(by=["Position", "Salary"])
nba.sort_values(by=["Position", "Salary"], ascending=True)
nba.sort_values(by=["Position", "Salary"], ascending=False)

nba.sort_values(by=["Position", "Salary"], ascending=[True, False])
nba.sort_values(by=["Position", "Salary"], ascending=[False, True])

,Name,Team,Position,Height,Weight,College,Salary
110,John Poulakidas,Dallas Mavericks,G-F,6-6,205.0,Yale,600000.0
416,Koby Brea,Phoenix Suns,G-F,6-7,215.0,Kentucky,600000.0
134,Spencer Jones,Denver Nuggets,G-F,6-7,225.0,Stanford,1300000.0
218,Jordan Miller,Los Angeles Clippers,G-F,6-7,195.0,Miami (FL),1300000.0
220,Kobe Sanders,Los Angeles Clippers,G-F,6-9,207.0,Nevada,1300000.0
...,...,...,...,...,...,...,...
325,Karlo Matkovic,New Orleans Pelicans,C,6-10,231.0,NaN,NaN
333,Ariel Hukporti,New York Knicks,C,7-0,251.0,NaN,NaN
354,Branden Carlson,Oklahoma City Thunder,C,7-0,220.0,Utah,NaN
371,Colin Castleton,Orlando Magic,C,6-11,250.0,Florida,NaN


## Sort with Ordered Categories
- By default, category values have no ranking.

In [101]:
hotels = pd.read_csv("hotel_bookings.csv")
hotels.head()

,Hotel,City,Room,Stars,Price,Rating,Nights,Guests,Season
0,Sunset Suites,Las Vegas,Standard,5,185.47,4.3,2,2,Summer
1,Harbor Hotel,Miami,Suite,4,315.38,3.1,4,3,Fall
2,Sunset Hotel,Nashville,Standard,3,112.52,3.5,7,3,Spring
3,Mountain Suites,Las Vegas,Deluxe,5,285.43,3.9,2,4,Spring
4,Ocean Hotel,New York,Deluxe,3,158.23,2.3,11,2,Spring


- The `nunique` methods returns a count of unique values.
- The `unique` method returns a list of all distinct/unique values.

In [102]:
hotels["Room"].nunique()
hotels["Room"].unique()

<ArrowStringArray>
['Standard', 'Suite', 'Deluxe', 'Presidential']
Length: 4, dtype: str

In [103]:
hotels["Room"] = hotels["Room"].astype("category")

In [104]:
hotels.sort_values("Room")

,Hotel,City,Room,Stars,Price,Rating,Nights,Guests,Season
97,Park Resort,Miami,Deluxe,3,242.72,3.0,2,1,Summer
75,Harbor Plaza,New York,Deluxe,4,238.20,3.3,8,1,Spring
74,Royal Plaza,New York,Deluxe,3,141.85,3.1,9,1,Winter
73,Skyline Hotel,Miami,Deluxe,4,199.01,4.4,2,3,Fall
133,Metro Resort,Chicago,Deluxe,5,310.65,5.0,1,1,Summer
...,...,...,...,...,...,...,...,...,...
156,Skyline Lodge,New York,Suite,4,338.69,3.1,6,2,Spring
47,Heritage Resort,New York,Suite,3,249.83,2.0,7,2,Fall
46,Ocean Resort,Chicago,Suite,4,333.27,3.8,1,3,Fall
166,Heritage Resort,Miami,Suite,4,372.71,3.4,2,2,Winter


- An **ordered** categorical assigns a rank to the sequence (e.g., "Standard" < "Deluxe" < "Suite" < "Presidential").
- We'll create a `CategoricalDtype` instance with an ordered list of categories.
- "Standard" comes before "Deluxe", which comes before "Suite".

In [105]:
room_type = pd.CategoricalDtype(
    categories=["Standard", "Deluxe", "Suite", "Presidential"], ordered=True
)

In [106]:
hotels["Room"] = hotels["Room"].astype(room_type)

- The `sort_values` method will use category order, not alphabetical order.

In [107]:
hotels.sort_values("Room")

,Hotel,City,Room,Stars,Price,Rating,Nights,Guests,Season
0,Sunset Suites,Las Vegas,Standard,5,185.47,4.3,2,2,Summer
141,Heritage Inn,Las Vegas,Standard,5,163.40,4.5,3,2,Winter
65,Harbor Plaza,New York,Standard,4,126.09,3.8,2,2,Fall
144,Ocean Suites,San Francisco,Standard,5,162.16,4.2,3,3,Fall
63,Mountain Lodge,Denver,Standard,5,177.09,4.4,5,4,Fall
...,...,...,...,...,...,...,...,...,...
183,Royal Resort,Nashville,Presidential,3,688.12,2.6,6,1,Summer
11,Skyline Resort,Las Vegas,Presidential,5,877.54,4.1,4,2,Winter
121,Sunset Suites,Austin,Presidential,4,618.53,3.4,6,1,Fall
128,Harbor Hotel,Las Vegas,Presidential,4,722.12,3.6,2,1,Spring


## Sort a DataFrame by its Index
- The `sort_index` method sorts the `DataFrame` by its index positions/labels.
- Assign back to the original variable to overwrite the old `DataFrame`.

In [108]:
nba = pd.read_csv("nba.csv").dropna(how="all").sort_values(["Position", "Name"])
nba

,Name,Team,Position,Height,Weight,College,Salary
386,Adem Bona,Philadelphia 76ers,C,6-10,235.0,UCLA,2300000.0
157,Al Horford,Golden State Warriors,C,6-9,240.0,Florida,5800000.0
175,Alperen Sengun,Houston Rockets,C,6-10,243.0,NaN,36500000.0
17,Amari Williams,Boston Celtics,C,6-11,250.0,Kentucky,2700000.0
387,Andre Drummond,Philadelphia 76ers,C,6-10,279.0,Connecticut,5000000.0
...,...,...,...,...,...,...,...
401,Tyrese Martin,Philadelphia 76ers,G-F,6-6,215.0,Connecticut,NaN
506,Vince Williams Jr.,Utah Jazz,G-F,6-6,210.0,Virginia Commonwealth,2400000.0
438,Vit Krejci,Portland Trail Blazers,G-F,6-8,195.0,NaN,2700000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0


In [109]:
nba.sort_index()
nba.sort_index(ascending=True)
nba.sort_index(ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
...,...,...,...,...,...,...,...
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0


In [110]:
nba = pd.read_csv("nba.csv", index_col="Name").dropna(how="all").sort_values("Position")
nba.head()

,Team,Position,Height,Weight,College,Salary
Name,,,,,,
Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN
Jock Landale,Atlanta Hawks,C,6-11,255.0,Saint Mary's,2300000.0
Mouhamed Gueye,Atlanta Hawks,C,6-10,210.0,Washington State,2100000.0
Onyeka Okongwu,Atlanta Hawks,C,6-8,235.0,USC,16000000.0
Amari Williams,Boston Celtics,C,6-11,250.0,Kentucky,2700000.0


In [111]:
nba.sort_index()
nba.sort_index(ascending=True)
nba.sort_index(ascending=False)

,Team,Position,Height,Weight,College,Salary
Name,,,,,,
Zyon Pullin,Minnesota Timberwolves,G,6-4,206.0,Florida,NaN
Zion Williamson,New Orleans Pelicans,F,6-7,284.0,Duke,42200000.0
Ziaire Williams,Brooklyn Nets,F,6-8,185.0,Stanford,6000000.0
Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,7700000.0
Zach LaVine,Sacramento Kings,G-F,6-5,200.0,UCLA,48200000.0
...,...,...,...,...,...,...
Aaron Holiday,Houston Rockets,G,6-0,185.0,UCLA,2300000.0
Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,31600000.0
AJ Johnson,Dallas Mavericks,G,6-5,160.0,NaN,3900000.0


## Rank Values with the rank Method
- The `rank` method assigns a numeric ranking to each `Series` value.
- Pandas will assign the same rank to equal values and create a "gap" in the dataset for the ranks.

In [112]:
nba = (
    pd.read_csv("nba.csv")
    .dropna(how="all")
    .fillna({"Salary": 0})
    .astype({"Salary": int})
)
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,0


In [113]:
nba["Salary"].rank()
nba["Salary"].rank(ascending=True)
nba["Salary"].rank(ascending=False)

0      286.0
1      180.5
2       62.5
3      428.5
4      500.5
       ...  
521    500.5
522     29.0
523    183.5
524    313.0
525    277.0
Name: Salary, Length: 526, dtype: float64

In [114]:
nba["Salary Rank"] = nba["Salary"].rank(ascending=False)

In [115]:
nba.sort_values("Salary", ascending=False)

,Name,Team,Position,Height,Weight,College,Salary,Salary Rank
392,Joel Embiid,Philadelphia 76ers,C,7-0,280.0,Kansas,64300000,1.0
22,Jayson Tatum,Boston Celtics,F,6-8,210.0,Duke,62700000,2.0
407,Devin Booker,Phoenix Suns,G,6-5,206.0,Kentucky,62100000,3.0
172,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,61100000,4.0
21,Jaylen Brown,Boston Celtics,G-F,6-6,223.0,California,59000000,5.5
...,...,...,...,...,...,...,...,...
64,Tosan Evbuomwan,Charlotte Hornets,F,6-8,217.0,Princeton,0,500.5
462,Emanuel Miller,San Antonio Spurs,F,6-6,215.0,TCU,0,500.5
74,Lachlan Olbrich,Chicago Bulls,F-C,6-10,235.0,NaN,0,500.5
181,JD Davison,Houston Rockets,G,6-3,175.0,Alabama,0,500.5


- The `method` parameter controls how Pandas assigns a rank when multiple values tie for the same rank.

In [116]:
scores = pd.Series([100, 90, 90, 80])
scores

0    100
1     90
2     90
3     80
dtype: int64

- The `"average"` value (default) uses the average of the rankings.

In [117]:
scores.rank(ascending=False, method="average")

0    1.0
1    2.5
2    2.5
3    4.0
dtype: float64

- The `"min"` value assigns all tied values the lowest rank.

In [118]:
scores.rank(ascending=False, method="min")

0    1.0
1    2.0
2    2.0
3    4.0
dtype: float64

- The `"max"` value assigns all tied values the highest rank.

In [119]:
scores.rank(ascending=False, method="max")

0    1.0
1    3.0
2    3.0
3    4.0
dtype: float64

- The `"dense"` value operates like `"min"` but has gaps in the ranking.
- The values of 90 and 90 tie for a rank of 2.
- The value of 100 is assigned a rank fo 3 instead of 4.

In [120]:
scores.rank(ascending=False, method="dense")

0    1.0
1    2.0
2    2.0
3    3.0
dtype: float64

- The `"first"` value breaks up ties based on the number's position.
- The first occurrence of the duplicate (90) in the `Series` gets the smaller rank.

In [121]:
scores.rank(ascending=False, method="first")

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64